Master.Organism = [
	{id:'Ac', name:'Aeromonas caviae', title:'<h1>Aeromonas <small> caviae</small></h1>'},
	{id:'Ah', name:'Aeromonas hydrophila', title:'<h1>Aeromonas <small> hydrophila</small></h1>'},
	{id:'As', name:'Aeromonas sobria', title:'<h1>Aeromonas <small> sobria</small></h1>'},
	{id:'Bac', name:'bacillus spoilage bacteria', title:'<h1>bacillus <small> spoilage bacteria</small></h1>'},
	{id:'Bc', name:'Bacillus cereus', title:'<h1>Bacillus <small> cereus</small></h1>'},
	{id:'Bl', name:'Bacillus licheniformis', title:'<h1>Bacillus <small> licheniformis</small></h1>'},
	{id:'Bs', name:'Bacillus subtilis', title:'<h1>Bacillus <small> subtilis</small></h1>'},
	{id:'Bt', name:'Brochothrix thermosphacta', title:'<h1>Brochothrix <small> thermosphacta</small></h1>'},
	{id:'Cbn', name:'Clostridium botulinum (non-prot.)', title:'<h1>Clostridium <small> botulinum (non-prot.)</small></h1>'},
	{id:'Cbp', name:'Clostridium botulinum (prot.)', title:'<h1>Clostridium <small> botulinum (prot.)</small></h1>'},
	{id:'Cj', name:'Campylobacter', title:'<h1>Campylobacter</h1>'},
	{id:'Cp', name:'Clostridium perfringens', title:'<h1>Clostridium <small> perfringens</small></h1>'},
	{id:'Ec', name:'Escherichia coli', title:'<h1>Escherichia <small> coli</small></h1>'},
	{id:'Ent', name:'enterobacteriaceae', title:'<h1>enterobacteriaceae</h1>'},
	{id:'Lab', name:'lactic acid bacteria', title:'<h1>lactic <small> acid bacteria</small></h1>'},
	{id:'Lm', name:'Listeria monocytogenes/innocua', title:'<h1>Listeria <small> monocytogenes/innocua</small></h1>'},
	{id:'Mi', name:'micrococci', title:'<h1>micrococci</h1>'},
	{id:'Po', name:'Paenibacillus odorifer', title:'<h1>Paenibacillus <small> odorifer</small></h1>'},
	{id:'Pp', name:'Photobacterium phosphoreum', title:'<h1>Photobacterium <small> phosphoreum</small></h1>'},
	{id:'Ps', name:'pseudomonads', title:'<h1>pseudomonads</h1>'},
	{id:'Psy', name:'psychrotrophic bacteria', title:'<h1>psychrotrophic <small> bacteria</small></h1>'},
	{id:'Sa', name:'Staphylococcus aureus', title:'<h1>Staphylococcus <small> aureus</small></h1>'},
	{id:'Sx', name:'Staphylococcus xylosus', title:'<h1>Staphylococcus <small> xylosus</small></h1>'},
	{id:'Sf', name:'Shigella flexneri and relatives', title:'<h1>Shigella <small> flexneri and relatives</small></h1>'},
	{id:'Ss', name:'salmonella spp', title:'<h1>salmonella <small> spp</small></h1>'},
	{id:'Ta', name:'aerobic total spoilage bacteria', title:'<h1>aerobic <small> total spoilage bacteria</small></h1>'},
	{id:'Vs', name:'vibrio spp.', title:'<h1>vibrio <small> spp.</small></h1>'},
	{id:'Ye', name:'Yersinia enterocolitica', title:'<h1>Yersinia <small> enterocolitica</small></h1>'},
	{id:'Sp', name:'Shewanella putrefaciens', title:'<h1>Shewanella <small> putrefaciens</small></h1>'},
	{id:'Sy', name:'spoilage yeast', title:'<h1>spoilage <small> yeast</small></h1>'},
	{id:'yeast', name:'yeast', title:'<h1>yeast</h1>'},
	{id:'Entc', name:'Enterococci', title:'<h1>Enterococci</h1>'},
	{id:'Bp', name:'Bacillus pumilus', title:'<h1>Bacillus <small> pumilus</small></h1>'},
	{id:'Cn_Psy', name:'non-proteolytic psychrotrophic clostridia', title:'<h1>non-proteolytic <small> psychrotrophic clostridia</small></h1>'},
	{id:'Ta_mould', name:'mould', title:'<h1>mould</h1>'},
	{id:'Hb', name:'halophilic bacteria', title:'<h1>halophilic <small> bacteria</small></h1>'},
	{id:'Ppx', name:'Paenibacillus polymyxa', title:'<h1>Paenibacillus <small> polymyxa</small></h1>'}
]
